# Generated by Django 3.1.4 on 2020-12-22 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_no', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('phone_number', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=60)),
                ('subject_name', models.CharField(max_length=60)),
                ('marks', models.IntegerField(default=0)),
                ('attendance', models.IntegerField(default=0)),
                ('index_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERMS.student', to_field='index_no')),
            ],
            options={
                'unique_together': {('index_no', 'subject_code')},
            },
        ),
    ]
